repos:
  - repo: local
    hooks:
      - id: ci
        name: Run CI (act)
        entry: act
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
