repos:
  - repo: https://github.com/JohnnyMorganz/stylua
    rev: v2.5.2
    hooks:
      - id: stylua

  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
