describe("File pattern filtering", function()
	local should_stage = require("timecapsule").should_stage
	it("should stage all files by default with exclusions", function()
		assert.is_false(should_stage("node_modules/file.js"))
		assert.is_false(should_stage("package-lock.json"))
		assert.is_false(should_stage("dist/output.js"))
		assert.is_false(should_stage("build/output.js"))

		assert.truthy(should_stage("src/app.js"))
		assert.truthy(should_stage("src/utils/helper.js"))
	end)

	it("should filter custom file_patterns", function()
		assert.truthy(should_stage("src/script.lua", { "*.lua" }))
		assert.is_false(should_stage("src/script.js", { "*.lua" }))
		assert.is_false(should_stage("package-lock.json", { "*.lua" }))
	end)

	it("should handle negation patterns", function()
		assert.truthy(should_stage("src/main.lua", { "*.lua", "!src/test.lua" }))
		assert.is_false(should_stage("src/test.lua", { "*.lua", "!src/test.lua" }))
	end)

	it("should handle multiple patterns with mixed inclusion/exclusion", function()
		assert.truthy(should_stage("src/app.js", { "*.js", "!node_modules/**", "!*.min.js" }))
		assert.is_false(should_stage("src/app.min.js", { "*.js", "!node_modules/**", "!*.min.js" }))
		assert.is_false(should_stage("node_modules/pkg/index.js", { "*.js", "!node_modules/**", "!*.min.js" }))
		assert.is_false(should_stage("dist/bundle.min.js", { "*.js", "!node_modules/**", "!*.min.js" }))
	end)
end)
