name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            neovim_version: nightly
          - os: ubuntu-22.04
            neovim_version: v0.10.0
          - os: ubuntu-22.04
            neovim_version: v0.9.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        with:
          neovim: ${{ matrix.neovim_version }}

      - name: Install plenary.nvim
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim .plenary

      - name: Run tests
        run: |
          export NVIM_RTP="${PWD}/.plenary:${PWD}"
          nvim --version
          nvim --headless -c "PlenaryBustedDirectory tests/ {}" -c "qa"

  lint:
    name: Lint code
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        with:
          neovim: nightly

      - name: Install stylua
        run: sudo apt-get update && sudo apt-get install -y stylua

      - name: Run stylua (Lua formatter)
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

      - name: Install luacheck
        run: |
          sudo apt-get update && sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck lua/
